//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidad
    {
        public int localidadId { get; set; }
        public int municipioId { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string altitud { get; set; }
        public string cve_carta { get; set; }
        public string ambito { get; set; }
        public int pobTotal { get; set; }
        public int pobMasculina { get; set; }
        public int pobFemenina { get; set; }
        public int totalViviendas { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lng { get; set; }
        public byte activo { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
